import Images from "../utils/images";

export const amenityList = [
  {
    num: "01",
    title: "24×7 Front Desk & Pilgrim Assistance",
    short: "Round-the-clock reception, Ram Mandir Darshan guidance, and elderly care assistance.",
    details: "Our caring local team is available day and night to assist with early morning Aarti passes, wheelchair arrangements, local transport, and spiritual itineraries.",
    image: Images.commonRoom1,
    tag: "Care & Support",
    rotation: -6.2,
    offsetX: -8,
    offsetY: 0,
  },
  {
    num: "02",
    title: "Complimentary High-Speed Wi-Fi",
    short: "Reliable, high-speed wireless connectivity throughout all rooms and guest lounges.",
    details: "Stay effortlessly connected with family back home, attend virtual meetings, or stream devotional bhajans without buffering.",
    image: Images.roomDeluxe,
    tag: "Connectivity",
    rotation: 6.8,
    offsetX: 12,
    offsetY: 8,
  },
  {
    num: "03",
    title: "Pure Vegetarian & Satvik Dining",
    short: "Wholesome, freshly prepared vegetarian meals and morning chai.",
    details: "Cooked in a pristine, sanctified kitchen adhering to authentic vegetarian standards. Enjoy traditional breakfast, warm milk, and refreshing beverages.",
    image: Images.godImage,
    tag: "Pure Living",
    rotation: -5.4,
    offsetX: -10,
    offsetY: 12,
  },
  {
    num: "04",
    title: "Air Conditioning & 24×7 Hot Water",
    short: "Modern climate control and dedicated geysers in all private attached bathrooms.",
    details: "Refresh after a day of pilgrimage with strong hot showers, fresh linens, and temperature-controlled comfort regardless of the season.",
    image: Images.washroom1,
    tag: "Comfort",
    rotation: 7.2,
    offsetX: 10,
    offsetY: 6,
  },
  {
    num: "05",
    title: "Secure On-Site Vehicle Parking",
    short: "Monitored, safe parking space directly adjacent to the property.",
    details: "Peace of mind for travellers arriving by private car, taxi, or family tempo traveler, with easy road access to Ayodhya's main corridors.",
    image: Images.mainGate,
    tag: "Convenience",
    rotation: -5.8,
    offsetX: -12,
    offsetY: 10,
  },
  {
    num: "06",
    title: "Passenger Lift & 100% Power Backup",
    short: "Elderly-friendly elevator access and generator backup for uninterrupted peace.",
    details: "Senior pilgrims can easily access upper floors with our modern elevator, and heavy-duty power backup ensures lights, fans, and Wi-Fi never stop.",
    image: Images.amenitiesImg,
    tag: "Accessibility",
    rotation: 5.5,
    offsetX: 8,
    offsetY: 14,
  },
];
